### ISSUE TITLE
blosc?

### ISSUE THREAD

**Issue by martindurant** [milesgranger/cramjam#110]
I may have asked this before....

numcodecs from zarr may be interested in depending on cramjam to simplify its build process ( https://github.com/zarr-developers/numcodecs/issues/464 ). The default and most common codecs used by zarr for new datasets is blosc v1. Blosc v2 also exists and is able to read v1. Is there any interest in adding blosc (v1 or v2) to cramjam? There seems to be quite a few crates in the area.

**Comment by milesgranger** [comment]
I have https://github.com/milesgranger/pyrus-cramjam/pull/107 which grew into covering a lot of the python-blosc2 API; nothing specific blocking it from going forward, just ran out of time.

> There seems to be quite a few crates in the area

I assume you're talking about blosc not blosc2; while I'd _much_ prefer blosc2 straight away. I only see one on crates.io and it's the sys crate. Meanwhile I've made the existing PR from my own implementation here https://github.com/milesgranger/blosc2-rs 

Again, I have no hesitancy to add blosc support, only a lack of time for free work these days (outside of expected maintenance). If there were funding available, I'd be happy to adjust the priority of it; otherwise it remains something I'm interested in completing as free-time presents itself over the next year.

**Comment by martindurant** [comment]
Thanks for the thoughts. I obviously don't have any sources of funding :|

cc @joshmoore

> I assume you're talking about blosc not blosc2

numcodecs does NOT yet support blosc 2, so now is a great time to think about how best to offer it since it seems to have [better performance](https://github.com/zarr-developers/numcodecs/issues/413#issuecomment-1727181584) in some cases.

**Comment by joshmoore** [comment]
> cc @joshmoore

Feel free to get in touch, @milesgranger, and/or take a look at https://github.com/zarr-developers/community/issues/64

> numcodecs does NOT yet support blosc 2

though there's of course https://github.com/zarr-developers/numcodecs/pull/463

cc: @FrancescAlted

**Comment by mkitti** [comment]
I would highly encourage all parties to move to Blosc2 unless you are willing to commit resources to Blosc1 maintenance.

**Comment by milesgranger** [comment]
First release having experimental blosc2 support (`cramjam.experimental.blosc2`) is [v2.8.4-rc1](https://github.com/milesgranger/cramjam/releases/tag/v2.8.4-rc1)
Closing this, but feedback is _very_ welcome in separate issues. 
xref https://github.com/milesgranger/cramjam/issues/159
