### ISSUE TITLE
Lower the default value for Brotli compression

### ISSUE THREAD

**Issue by vincentsarago** [milesgranger/cramjam#187]
Dear @milesgranger,
As usual, thanks for all the work on this and your other libraries. While trying to compare results from https://github.com/developmentseed/starlette-cramjam and other FastAPI Middleware I was surprised to see that the default level value for the brotli compressor was set to 11

https://github.com/milesgranger/cramjam/blob/a23b9eac294f0a9fcc5ba2bb7c3056eba40e61a6/src/brotli.rs#L15

while for the other compression (e.g deflate) 

https://github.com/milesgranger/cramjam/blob/a23b9eac294f0a9fcc5ba2bb7c3056eba40e61a6/src/deflate.rs#L15

they were set to a `middle` values

with starlette-cramjam, it's really hard to set level values individually so I was hopping that `default` values to me kinda good (but not perfect). Can I ask what was the motivation for having the maximum value (11) set for the Brotli compression? 

```python
import httpx
import cramjam 

page = httpx.get("https://github.com/developmentseed/starlette-cramjam").content

%timeit cramjam.brotli.compress(page)
# 282 ms ± 3.86 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

cramjam.brotli.compress(page).len()
# 39294

%timeit cramjam.deflate.compress(page)
# 4.32 ms ± 364 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

cramjam.deflate.compress(page).len()
# 55199

# Set level to 6
%timeit cramjam.brotli.compress(page, level=6)
# 4.32 ms ± 74.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

cramjam.brotli.compress(page, level=6).len()
# 44069
```

Side Question, it's not clear to me what are the `max` values for the level. e.g for deflate I can use `level=11` while by definition deflate max level is 9 🤷 

```python
cramjam.deflate.compress(page, level=11).len()
# 55037

cramjam.deflate.compress(page, level=9).len()
# 55040
```

~~Edit: 😬 those timing results were done with 2.7.0, let me use the latest version~~

**Comment by milesgranger** [comment]
Hey there! 

I believe it was taken to match python-brotli: https://github.com/google/brotli/blob/350100a5bb9d9671aca85213b2ec7a70a361b0cd/python/brotli.py#L25

Then looking around, I also notice javascript's brotli impl has it at 11 as well:
https://github.com/foliojs/brotli.js/blob/35ab0b5f340762231266367a10b60e386e042ad9/compress.js#L19

So given this, I think we should follow the pattern.

> Side Question, it's not clear to me what are the max values for the level. e.g for deflate I can use level=11 while by definition deflate max level is 9

Hrm, good question. I do see the [deflate](https://pypi.org/project/deflate/) package will take up to level 12 though. Anyway, cramjam could be improved by checking the max allowed. I don't think it checks this much anywhere actually. I think I've maybe (wrongly?) assumed the underlying library would handle it as needed. 

For example Rust's deflate implementation I'm using (flate2) is happily accepting any values:
https://github.com/cramjam/libcramjam/blob/fb66c01d80e5a2bfbd6ff94aed47af49c87aede9/src/deflate.rs#L30

That's not the case w/  `ideflate` though:
```python
In [28]: cramjam.experimental.ideflate.compress(data, level=13)
---------------------------------------------------------------------------
CompressionError                          Traceback (most recent call last)
Cell In[28], line 1
----> 1 cramjam.experimental.ideflate.compress(data, level=13)

CompressionError: Compression level 13 not supported, must be one of [0, 1, 3] (Exit code: None)
```

SoooOooOoo now just thinking through it, I'm rather tempted to say, "oh well". I think it'd be weird to handle the values as the middle man when the implementation I'm passing the value to is happily accepting it and not breaking anything. The better way seems to be opening PRs to these other Rust libs to enforce any bounds. Which isn't an absurd thing I suppose; but probably not high on my priority list.

---

BTW, since [v2.9.0](https://github.com/milesgranger/cramjam/releases/tag/v2.9.0) we have ISA-L backed gzip, deflate and zlib: `cramjam.experimental.igzip/ideflate/izlib` which are much faster. They're only available on 64bit systems though, and not as battle tested as the regular implementations.

**Comment by vincentsarago** [comment]
thanks @milesgranger 🙏 

👍 let's keep 11 as default value 

> SoooOooOoo now just thinking through it, I'm rather tempted to say, "oh well". I think it'd be weird to handle the values as the middle man when the implementation I'm passing the value to is happily accepting it and not breaking anything. The better way seems to be opening PRs to these other Rust libs to enforce any bounds. Which isn't an absurd thing I suppose; but probably not high on my priority list.

Totally makes sense

**Comment by milesgranger** [comment]
Not a bad idea! Something like `cramjam.gzip.set_default_level(5)`?
Guess there might be _some_ performance impact when level isn't explicitly provided as it'd have to access a mutable global, maybe a [LazyLock](https://doc.rust-lang.org/std/sync/struct.LazyLock.html).
